---
name: ScrimAS
version: 0.6.0
main: OnlyJaiden\ScrimAS\Main
api: 4.0.0
src-namespace-prefix: OnlyJaiden\ScrimAS

commands:
  alerts:
    description: Stop getting annoying alerts.
    permission: ScrimAS.alerts

permissions:
  ScrimAS.alerts:
    default: op
    description: Get alerts from ac.
...
